name: Python application

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        ref: ${{ github.head_ref }}

    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"

    - name: Remove existing requirements.txt file (if it exists)
      run: rm -rf requirements.txt

    - name: create requirements.txt
      run: |
        pip3 freeze > requirements.txt

    - name: Commit requirements.txt
      run: |
        git config --local user.email "github@Actions.com"
        git config --local user.name "github-actions[bot]"
        git add requirements.txt
        git commit -am "Export requirements.txt"
        git push origin HEAD:${{ github.head_ref }}
      continue-on-error: true

